name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install QT
        uses: jurplel/install-qt-action@v3.3.0
        with:
          version: '6.2.0'

      - name: Configure project
        run: |
          cd build
          cmake .
          
      - name: Build project
        run: |
          make install
          
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
